// BASE_URL
export let BASE_URL = 'http://localhost:3003/api';

// DASHBOARD
export let SET_SUMMARY = 'SET_SUMMARY';

// BILLINGCYCLES
export let SET_BILLINGCYCLE = 'SET_BILLINGCYCLE';
export let SET_MESSAGE_SUCCESS = 'SET_MESSAGE_SUCCESS';
export let SET_MESSAGE_ERROR = 'SET_MESSAGE_ERROR';
export let SET_ITEM_TO_EDIT = 'SET_ITEM_TO_EDIT';
export let RESET_ITEM_TO_EDIT = 'RESET_ITEM_TO_EDIT';

//FORM
export let SET_VALUES_FORM = 'SET_VALUES_FORM';
export let RESET_VALUES_FORM = 'RESET_VALUES';
export let SET_NEW_CREDIT = 'SET_NEW_CREDIT';
export let SET_NEW_DEBIT = 'SET_NEW_DEBIT';
export let ADD_CREDIT_VALUES = 'ADD_CREDIT_VALUES';
export let ADD_DEBIT_VALUES = 'ADD_DEBIT_VALUES';

//TABS
export let SET_SHOW_TAB = 'SET_SHOW_TAB';
export let SET_TABS_VISIBLE = 'SET_TABS_VISIBLE';

// AUTH

export let SET_MODE_AUTH = 'SET_MODE_AUTH';
export let SET_VALUES_AUTH = 'SET_VALUES_AUTH';
export let SET_USER_AUTH = 'SET_USER_AUTH';
export let SET_USER_TOKEN = 'SET_USER_TOKEN';
export let RESET_AUTH = 'RESET_AUTH';
export let SET_AUTH_ERRORS = 'SET_AUTH_ERRORS';
export let RESET_AUTH_ERRORS = 'RESET_AUTH_ERRORS';
