// AUTH
export const AUTH_SET_VALUES = 'AUTH_SET_VALUES';
export const AUTH_SET_ERRORS = 'AUTH_SET_ERRORS';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_USER_TOKEN = 'AUTH_SET_USER_TOKEN';
export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';

// CONTEXT
export const CONTEXT_SET_LOADING = 'CONTEXT_SET_LOADING';
export const CONTEXT_SET_DATE = 'CONTEXT_SET_DATE';
export const CONTEXT_RESET_STATE = 'CONTEXT_RESET_STATE';
export const CONTEXT_CHANGE_VALUE = 'CONTEXT_CHANGE_VALUE';
export const CONTEXT_CHANGE_PERCENT = 'CONTEXT_CHANGE_PERCENT';
export const CONTEXT_WEEK_TO_PDF = 'CONTEXT_WEEK_TO_PDF';

// CLOSING
export const CLOSING_SET_DATA = 'CLOSING_SET_DATA';
export const CLOSING_RESET_STATE = 'CLOSING_RESET_STATE';
export const CLOSING_SET_DAY_EDIT = 'CLOSING_SET_DAY_EDIT';
export const CLOSING_RESET_DAY_EDIT = 'CLOSING_RESET_DAY_EDIT';

//ADMIN
export const ADMIN_SET_USERS = 'ADMIN_SET_USERS';

export const CONTEXT_SET_MESSAGE = 'CONTEXT_SET_MESSAGE';
