// AUTH
export const AUTH_SET_VALUES = 'AUTH_SET_VALUES';
export const AUTH_SET_ERRORS = 'AUTH_SET_ERRORS';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_USER_TOKEN = 'AUTH_SET_USER_TOKEN';
export const AUTH_RESET_STATE = 'AUTH_RESET_STATE';

// CONTEXT
export const CONTEXT_SET_LOADING = 'CONTEXT_SET_LOADING';
export const CONTEXT_SET_DATE = 'CONTEXT_SET_DATE';

export const CONTEXT_CHANGE_VALUE = 'CONTEXT_CHANGE_VALUE';
export const CONTEXT_CHANGE_PERCENT = 'CONTEXT_CHANGE_PERCENT';

export const CONTEXT_WEEK_TO_PDF = 'CONTEXT_WEEK_TO_PDF';

// CLOSING
export const CLOSING_SET_DATA = 'CLOSING_SET_DATA';

export const CLOSING_SET_VALUE_DAY = 'CLOSING_SET_VALUE_DAY';
export const CLOSING_UPDATE_VALUE_DAY = 'CLOSING_UPDATE_VALUE_DAY';
export const CLOSING_DELETE_VALUE_DAY = 'CLOSING_DELETE_VALUE_DAY';
export const CLOSING_SET_DATE = 'CLOSING_SET_DATE';
export const CLOSING_SET_TOTAL_DAY = 'CLOSING_SET_TOTAL_DAY';
export const CLOSING_RESET_DAY = 'CLOSING_RESET_DAY';

export const CLOSING_ADD_DAY_IN_WEEK = 'CLOSING_ADD_DAY_IN_WEEK';
export const CLOSING_SET_TOTAL_WEEK = 'CLOSING_SET_TOTAL_WEEK';
export const CLOSING_RESET_WEEK = 'CLOSING_RESET_WEEK';

export const CLOSING_ADD_WEEK_IN_AGGREGATE = 'CLOSING_ADD_WEEK_IN_AGGREGATE';
export const CLOSING_SET_TOTAL_AGGREGATE = 'CLOSING_SET_TOTAL_AGGREGATE';

export const CLOSING_SET_DAY_EDIT = 'CLOSING_SET_DAY_EDIT';
export const CLOSING_RESET_DAY_EDIT = 'CLOSING_RESET_DAY_EDIT';
